'''
   Example on how to plot latitude/longitude points into a map
   downloaded from Google Maps and matplotlib.
'''
import math
import ConfigParser
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from GoogleMapsCoord import GoogleMapsCoord



# Read the map details from file generated by GoogleMapsDownloader
config = ConfigParser.ConfigParser()
config.read('map_desc.txt')

ref_lat = float(config.get('map', 'lat_ref'))
ref_lng = float(config.get('map', 'lng_ref'))
zoom = int(config.get('map', 'zoom_ref'))
tile_height = int(config.get('map', 'height'))
tile_width = int(config.get('map', 'width'))

# Create map image
img = mpimg.imread('map.png')
fig, ax = plt.subplots()
ax.imshow(img)

# Calculate the (0, 0) position
ref_x, ref_y = GoogleMapsCoord.latlngToTile(ref_lat, ref_lng, zoom)
ref_x = ref_x * GoogleMapsCoord.TITLE_SIZE
ref_y = ref_y * GoogleMapsCoord.TITLE_SIZE

print '(0, 0) Pixel Position: ', ref_x, ref_y

# Plot point 1
x, y = GoogleMapsCoord.latlngToPixel(43.405109, -83.885867, zoom)
new_x = x - ref_x
new_y = y - ref_y

print 'Point 1:', new_x, new_y
ax.plot(new_x, new_y, ".r")

# Plot point 2
x, y = GoogleMapsCoord.latlngToPixel(43.404715, -83.885964, zoom)
new_x = x - ref_x
new_y = y - ref_y

print 'Point 2:', new_x, new_y
ax.plot(new_x, new_y, ".r")

# Plot point 3
x, y = GoogleMapsCoord.latlngToPixel(43.403669, -83.884159, zoom)
new_x = x - ref_x
new_y = y - ref_y

print 'Point 3:', new_x, new_y
ax.plot(new_x, new_y, ".r")

# Show plot
plt.show()